# Generated by Django 5.0.4 on 2024-06-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alex', '0004_rev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rev',
            old_name='description',
            new_name='descriere',
        ),
        migrations.RenameField(
            model_name='rev',
            old_name='trainer',
            new_name='excursia',
        ),
        migrations.RenameField(
            model_name='rev',
            old_name='first_name',
            new_name='nume',
        ),
        migrations.RenameField(
            model_name='rev',
            old_name='last_name',
            new_name='prenumele',
        ),
    ]
