# Generated by Django 5.0.4 on 2024-06-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alex', '0005_rename_description_rev_descriere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rev',
            name='nota',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=6, null=True),
        ),
    ]
