# Generated by Django 5.0.4 on 2024-06-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alex', '0006_rev_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rev',
            name='nota',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=6),
        ),
    ]
